apiVersion: v1
kind: Namespace
metadata:
  name: dev  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: dev
spec:
  replicas: 1 # 1 pod should always exist
  selector:
    matchLabels:
      app: login
  template: # Pod Template
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: c1
        image: ravi2krishna/login-2505
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      nodePort: 30008